services:
  php-fpm:
    container_name: php-fpm
    build:
      context: ./../
      dockerfile: ./docker/php-fpm/Dockerfile
      args:
        - PUID=${PUID}
        - PGID=${PGID}
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - /var/www/vendor/
      - ./../:/var/www/

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ..:/var/www:rw
    depends_on:
      - php-fpm

  postgres:
    container_name: postgres
    build:
      context: ./postgres
    ports:
      - ${PGSQL_PORT}:5432
    env_file: postgres/.env
    volumes:
      - pgsql:/var/lib/postgresql/data:rw
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 1s
      timeout: 100s
      retries: 50

volumes:
  pgsql:
